Constructora/urls.py
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.contrib.auth.views import login
urlpatterns = [
    url(r'^', include('home.urls' ,namespace='home')),
    url(r'^admin/', admin.site.urls),




    # para  la app de producto


    url(r'^producto/', include('producto.urls' ,namespace='producto')),

     # para  la app de cliente

    url(r'^cliente/', include('cliente.urls' ,namespace='cliente')),


    #url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),




   

  

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cliente/urls.py
from django.conf.urls import url , include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [


	url(r'^registro/$', views.cliente_nuevo, name='cliente_nuevo'),
	url(r'^login/$', views.authentication, name='login'),
	url(r'^logout$', auth_views.logout, {'next_page': 'login/'}, name='logout'),
	url(r'^listar/$', views.cliente_listar, name='cliente_listar'),
	url(r'^eliminar/(?P<id_cliente>\d+)$', views.cliente_eliminar, name='cliente_eliminar'),
	url(r'^editar/(?P<id_cliente>\d+)$', views.cliente_editar, name='cliente_editar'),
	
	


	

]

home/urls.py
from django.conf.urls import url , include
from . import views



urlpatterns = [
	url(r'^$', views.mostrar_inicio, name='index'),
	url(r'^contactos/$', views.mostrar_contactos, name='mostrar_contactos'),
	url(r'^shopping-cart/$', views.mostrar_carro, name='mostrar_carro'),
	url(r'^quienes_somos/$', views.mostrar_quienes, name='mostrar_quienes'),
	url(r'^maquinaria/$', views.mostrar_maquinaria, name='mostrar_maquinaria'),
	url(r'^herramientas/$', views.mostrar_herramienta, name='mostrar_herramienta'),
	url(r'^detalle/$', views.mostrar_detalle, name='mostrar_detalle'),
	url(r'^login/$', views.mostrar_login , name='mostrar_login'),

	# admin

	#url(r'^administrador/$', views.mostrar_admin, name='mostrar_admin'),





	#url(r'^register/$', views.UserFormView.as_view(), name='register'),
	#url(r'^new_user/$', views.usuario),
	
	# usuarios
		
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	#url(r'^admin/',views.add_user),

]

producto/urls.py
from django.conf.urls import url , include
from . import views

urlpatterns = [


	url(r'^nuevo/$', views.producto_nuevo, name='producto_nuevo'),
	url(r'^listar/$', views.producto_listar, name='producto_listar'),
	url(r'^tipo/$', views.producto_tipo_nuevo, name='producto_tipo_nuevo'),
	url(r'^tipo_listar/$', views.producto_tipo_listar, name='producto_tipo_listar'),
	url(r'^tipo_editar/(?P<id_tipo>\d+)$', views.producto_tipo_editar, name='producto_tipo_editar'),
	url(r'^tipo_eliminar/(?P<id_tipo>\d+)$', views.producto_tipo_eliminar, name='producto_tipo_eliminar'),
	url(r'^eliminar/(?P<id_producto>\d+)$', views.producto_eliminar, name='producto_eliminar'),
	url(r'^editar/(?P<id_producto>\d+)$', views.producto_editar, name='producto_editar'),

	# url de cart

	url(r'^cart/(?P<id_producto>\d+)/(?P<quantity>\d+)$', views.add_to_cart, name='add_to_cart'),
	url(r'^get_cart/$', views.get_cart, name='get_cart'),
	url(r'^remove_from_cart/(?P<id_producto>\d+)$', views.remove_from_cart, name='remove_from_cart'),
	
	


	

]

home/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from cliente.forms import UserForm, ClienteForm

# Create your views here.


def mostrar_inicio(request):
	return render(request, 'home/index.html',{})

def mostrar_contactos(request):
	return render(request, 'home/contact.html',{})

def mostrar_quienes(request):
	return render(request, 'home/elements.html',{})

def mostrar_carro(request):
	return render(request, 'producto/shopping-cart.html',{})

def mostrar_maquinaria(request):
	return render(request, 'home/maquinaria.html',{})


def mostrar_herramienta(request):
	return render(request, 'home/herramienta.html',{})


def mostrar_detalle(request):
	return render(request, 'home/detalle_reserva.html',{})

def mostrar_login(request):
	cliente_form = ClienteForm()
	user_form = UserForm()

	context = {
		'cliente_form': cliente_form,
		'user_form': user_form,
	}
	return render(request, 'home/login.html',context)

def mostrar_alquiler(request):
	return render(request, 'aplicacion/index1.html',{})

# administrador

templates/home/cliente_eliminar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}



{% block contenido7 %}
		<form method="POST"> {% csrf_token %}
				<h2>¿DESEA DAR DE BAJA EL REGISTRO?</h2>
				<button type="submit">Si, eliminar</button>
				<a href="{% url 'producto:producto_listar' %}">Cancelar</a>
		</form>

{% endblock %}

templates/home/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido1 %}

<!-- Titlebar
================================================== -->
<section class="titlebar margin-bottom-0">
<div class="container">
	<div class="sixteen columns">
		<h2>Contacto</h2>

		<nav id="breadcrumbs">
		
		</nav>
	</div>
</div>
</section>


<!-- Content
================================================== -->

<!-- Container -->
<div class="container fullwidth-element">

	<!-- Google Maps -->
	<section class="google-map-container">
		<div >
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7960.234378954259!2d-79.21088477577399!3d-3.996320297995821!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x38c1d263184a7212!2sEncofrados+%26+construcciones+%22GRANDA%22!5e0!3m2!1ses!2sec!4v1499701509737" width="1060" height="430" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
	</section>
	<!-- Google Maps / End -->

</div>
<!-- Container / End -->


<!-- Container -->
<div class="container">
<div class="four columns">

	<!-- Information -->
	<div class="widget margin-top-10">
		<div class="accordion">

			<!-- Section 1 -->
			<h3><span class="ui-accordion-header-icon ui-icon ui-accordion-icon"></span><i class="fa fa-thumb-tack"></i> Direccion</h3>
			<div>
				<ul class="contact-informations margin-top-0">
					<li><span class="address">Manuel Carrión Pinzano</span></li>
					<li><span class="address">Manuel Palacios Y Epiclachima</span></li>
				</ul>
			</div>

			<!-- Section 2 -->
			<h3><span class="ui-accordion-header-icon ui-icon ui-accordion-icon"></span><i class="fa fa-user"></i> Contactos</h3>
			<div>
				<ul class="contact-informations second">
					<li><i class="fa fa-phone"></i> <p>2575 236</p></li>
					<li><i class="fa fa-phone"></i> <p>0998866491</p></li>
					<li><i class="fa fa-envelope"></i> <p>mencofradosgranda@gmail.com</p></li>
					<!--<li><i class="fa fa-globe"></i> <p>www.example.com</p></li>-->
				</ul>
			</div>

		</div>
	</div>

	<!-- Social -->
	<!--<div class="widget">
		<h3 class="headline">Get Social</h3><span class="line margin-bottom-25"></span><div class="clearfix"></div>
		<ul class="social-icons">
			<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
			<li><a class="dribbble" href="#"><i class="icon-dribbble"></i></a></li>
			<li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
			<li><a class="pinterest" href="#"><i class="icon-pinterest"></i></a></li>
			<li><a class="forrst" href="#"><i class="icon-forrst"></i></a></li>
			<li><a class="rss" href="#"><i class="icon-rss"></i></a></li>
		</ul>
		<div class="clearfix"></div>
	<br>
	</div> -->

</div>

<!-- Contact Form -->
<div class="twelve columns">
	<div class="extra-padding left">
		<h3 class="headline">Enviar mensaje</h3><span class="line margin-bottom-25"></span><div class="clearfix"></div>

		<!-- Contact Form -->
		<section id="contact">

			<!-- Success Message -->
			<mark id="message"></mark>

			<!-- Form -->
			<form method="post" name="contactform" id="contactform">

				<fieldset>

					<div>
						<label>Name:</label>
						<input name="name" type="text" id="name" />
					</div>

					<div>
						<label >Email: <span>*</span></label>
						<input name="email" type="email" id="email" pattern="^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$" />
					</div>

					<div>
						<label>Message: <span>*</span></label>
						<textarea name="comment" cols="40" rows="3" id="comment" spellcheck="true"></textarea>
					</div>

				</fieldset>
				<div id="result"></div>
				<input type="submit" class="submit" id="submit" value="Enviar" />
				<div class="clearfix"></div>
			</form>

		</section>
		<!-- Contact Form / End -->
	</div>
</div>
</div>
<!-- Container / End -->

<div class="margin-top-50"></div>


<!-- Footer
================================================== -->

<!-- Back To Top Button -->
<div id="backtotop"><a href="#"></a></div>

</div>


<!-- Java Script
================================================== -->
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="scripts/jquery.jpanelmenu.js"></script>
<script src="scripts/jquery.themepunch.plugins.min.js"></script>
<script src="scripts/jquery.themepunch.revolution.min.js"></script>
<script src="scripts/jquery.themepunch.showbizpro.min.js"></script>
<script src="scripts/jquery.magnific-popup.min.js"></script>
<script src="scripts/hoverIntent.js"></script>
<script src="scripts/superfish.js"></script>
<script src="scripts/jquery.pureparallax.js"></script>
<script src="scripts/jquery.pricefilter.js"></script>
<script src="scripts/jquery.selectric.min.js"></script>
<script src="scripts/jquery.royalslider.min.js"></script>
<script src="scripts/SelectBox.js"></script>
<script src="scripts/modernizr.custom.js"></script>
<script src="scripts/waypoints.min.js"></script>
<script src="scripts/jquery.flexslider-min.js"></script>
<script src="scripts/jquery.counterup.min.js"></script>
<script src="scripts/jquery.tooltips.min.js"></script>
<script src="scripts/jquery.isotope.min.js"></script>
<script src="scripts/puregrid.js"></script>
<script src="scripts/stacktable.js"></script>
<script src="scripts/custom.js"></script>

<script src="scripts/jquery.gmaps.min.js"></script>

<script type="text/javascript">
	(function($){
		$(document).ready(function(){

			$('#googlemaps').gMap({
				maptype: 'ROADMAP',
				scrollwheel: false,
				zoom: 13,
				markers: [
					{
						address: 'New York, 45 Park Avenue', // Your Adress Here
						html: '<strong>Our Office</strong><br>45 Park Avenue, Apt. 303 </br>New York, NY 10016 ',
						popup: true,
					}
				],
			});

		   });

	})(this.jQuery);
</script>


<!-- Style Switcher
================================================== -->
<script src="scripts/switcher.js"></script>


{% endblock %}

templates/home/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block header %}

<!-- Top Bar
================================================== -->
<div id="top-bar">
	<div class="container">

		<!-- Top Bar Menu -->
		<div class="ten columns">
			<ul class="top-bar-menu">
				<li><i class="fa fa-phone"></i> 2575 236 </li>
				<li><i class="fa fa-envelope"></i> <a href="#">encofradosgranda@gmail.com</a></li>
				<li>
					<!--<div class="top-bar-dropdown">
						<span>English</span>
						<ul class="options">
							<li><div class="arrow"></div></li>
							<li><a href="#">English</a></li>
							<li><a href="#">Polish</a></li>
							<li><a href="#">Deutsch</a></li>
						</ul>
					</div>
				</li>
				<li>
					<div class="top-bar-dropdown">
						<span>USD</span>
						<ul class="options">
							<li><div class="arrow"></div></li>
							<li><a href="#">USD</a></li>
							<li><a href="#">PLN</a></li>
							<li><a href="#">EUR</a></li>
						</ul>
					</div>-->
				</li>
			</ul>
		</div>

		<!-- Social Icons -->
		<div class="six columns">
			<ul class="social-icons">
				<li><a class="facebook" href="#"><i class="icon-facebook"></i></a></li>
				<li><a class="twitter" href="#"><i class="icon-twitter"></i></a></li>
				<li><a class="dribbble" href="#"><i class="icon-dribbble"></i></a></li>
				<li><a class="gplus" href="#"><i class="icon-gplus"></i></a></li>
				<li><a class="pinterest" href="#"><i class="icon-pinterest"></i></a></li>
			</ul>
		</div>

	</div>
</div>

<div class="clearfix"></div>


<!-- Header
================================================== -->
<div class="container">


	<!-- Logo -->
	<div class="four columns">
		<div id="logo">
			<h1><a href="#"><img src="{% static 'images/fondo.png' %}" alt="Trizzy" /></a>Construcciones Granda</h1>
		</div>
	</div>


	<!-- Additional Menu -->
	<div class="twelve columns">
		<div id="additional-menu">
			<ul>
					
			</ul>
		</div>
	</div>


	<!-- Shopping Cart -->
	<div class="twelve columns">

		<div id="cart">

			<!-- Button -->
			<div class="cart-btn">
				<a href="{% url 'producto:get_cart' %}" class="button adc">$178.00</a>
			</div>

			<!--<div class="cart-list">

			<div class="arrow"></div>

				<div class="cart-amount">
					<span>2 items in the shopping cart</span>
				</div>

					<ul>
						<li>
							<a href="#"><img src="images/small_product_list_08.jpg" alt="" /></a>
							<a href="#">Converse All Star Trainers</a>
							<span>1 x $79.00</span>
							<div class="clearfix"></div>
						</li>

						<li>
							<a href="#"><img src="images/small_product_list_09.jpg" alt="" /></a>
							<a href="#">Tommy Hilfiger <br /> Shirt Beat</a>
							<span>1 x $99.00</span>
							<div class="clearfix"></div>
						</li>
					</ul>

				<div class="cart-buttons button">
					<a href="{% url 'producto:get_cart' %}" class="view-cart" ><span data-hover="View Cart"><span>View Cart</span></span></a> 
					
				</div>
				<div class="clearfix">

				</div>
			</div>-->

		</div>

		<!-- Search -->
		<nav class="top-search">
			<form action="#" method="get">
				<button><i class="fa fa-search"></i></button>
				<input class="search-field" type="text" placeholder="Search" value=""/>
			</form>
		</nav>

	</div>

</div>

{% endblock%}

{% block slide%}
	<!-- Navigation
================================================== -->
<div class="container">
	<div class="sixteen columns">
		
		<a href="/" class="menu-trigger"><i class="fa fa-bars"></i> Menu</a>

		<nav id="navigation">
			<ul class="menu" id="responsive">

				<li><a href="/" class="current homepage" id="current">Home</a></li>

				<!--<li class="dropdown">
					<a href="#">Shop</a>
					<ul>
						<li><a href="shop-with-sidebar.html">Shop With Sidebar</a></li>
						<li><a href="shop-with-adv-search.html">Shop With Adv. Search</a></li>
						<li><a href="shop-full-width.html">Shop Full Width</a></li>
						<li><a href="checkout-billing-details.html">Checkout Pages</a></li>
						<li><a href="shop-categories-grid.html">Categories Grid</a></li>
						<li><a href="single-product-page.html">Single Product Page</a></li>
						<li><a href="variable-product-page.html">Variable Product Page</a></li>
						<li><a href="wishlist.html">Wishlist Page</a></li>
						<li><a href="shopping-cart.html">Shopping Cart</a></li>
					</ul>
				</li> -->


				<li class="dropdown">
					<a href="{% url 'producto:producto_listar' %}">PRODUCTOS</a>
					<!--<ul>
						<li><a href="{% url 'home:mostrar_herramienta' %}">Herramienta</a></li>
						<li><a href="{% url 'home:mostrar_maquinaria' %}">Maquinaria</a></li>
					</ul> -->
				</li>

				<li class="dropdown">
					<a href="{% url 'home:mostrar_quienes' %}">QUIENES SOMOS </a>
					<!--<ul>
						<li><a href="elements.html">Elements</a></li>
						<li><a href="typography.html">Typography</a></li>
						<li><a href="pricing-tables.html">Pricing Tables</a></li>
						<li><a href="icons.html">Icons</a></li>
					</ul>-->
				</li>


				<li class="dropdown">
					<a href="{% url 'home:mostrar_contactos' %}">CONTACTOS</a>
					<!--<ul>
						<li><a href="portfolio-3-columns.html">3 Columns</a></li>
						<li><a href="portfolio-4-columns.html">4 Columns</a></li>
						<li><a href="portfolio-dynamic-grid.html">Dynamic Grid</a></li>
						<li><a href="single-project.html">Single Project</a></li>
					</ul> -->
				</li>

				<li class="dropdown">
					<a href="#">Administrar</a>
					<ul>
						<li><a href="{% url 'producto:producto_listar' %}">Productos</a></li>
						<li><a href="{% url 'cliente:cliente_listar' %}">Clientes</a></li>
					</ul> 
				</li>
				

				
					
				</li>


				<!--<li class="demo-button">
				  <a href="#">Get This Theme</a>
				</li>-->

			</ul>
		</nav>
	</div>
</div>

{% endblock %}
{% block contenido1 %}
<!-- Slider
================================================== -->
<div class="container fullwidth-element home-slider">

	<div class="tp-banner-container">
		<div class="tp-banner">
			<ul>

				<!-- Slide 1  -->
				<li data-transition="fade" data-slotamount="7" data-masterspeed="1000">
 					<img src="{% static 'images/slider.jpg' %}"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption dark sfb fadeout" data-x="750" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2>Bienvenido</h2>
						<!--<h3>Every cut and colour</h3> -->
						<!--<a href="shop-with-sidebar.html" class="caption-btn">Shop The Collection</a> -->
					</div>
				</li>


				<!-- Slide 2  -->
				<li data-transition="zoomout" data-slotamount="7" data-masterspeed="1500" >
					<img src="{% static 'images/slider.jpg' %}"  alt="slidebg1"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption sfb fadeout" data-x="145" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2>Dress Sharp</h2>
						
					</div>
				</li>


				<!-- Slide 3  -->
				<li data-transition="fadetotopfadefrombottom" data-slotamount="7" data-masterspeed="1000">
 					<img src="{% static 'images/concretera.jpg' %}"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption dark sfb fadeout" data-x="850" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2>New In</h2>
						
					</div>
				</li>

				<!-- Slide 4  -->

				<li data-transition="fadetotopfadefrombottom" data-slotamount="7" data-masterspeed="1000">
 					<img src="{% static 'images/concretera.jpg' %}"  alt="darkblurbg"  data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
 					<div class="caption dark sfb fadeout" data-x="850" data-y="170" data-speed="400" data-start="800"  data-easing="Power4.easeOut">
						<h2>New In</h2>
						
					</div>
				</li>


			</ul>
		</div>
	</div>
</div>
{% endblock %}

{% block contenido2 %}


{% endblock %}

{% block contenido3 %}
	
{% endblock %}

{% block contenido4 %}
	

{% endblock %}-->

{% block footer %}

<!-- Footer
================================================== -->
<div id="footer">

	<!-- Container -->
	<div class="container">

		<div class="four columns">
			<img src="{% static 'images/carretilla.gif' %}" alt="" class="margin-top-10"/>
			
		</div>

		<div class="four columns">

			<!-- Headline -->
			<h3 class="headline footer">DIRECCION</h3>
			<span class="line"></span>
			<div class="clearfix"></div>

			<ul class="footer-links">
				<li>Manuel Carrión Pinzano e/</li>
				<li>Manuel Palacios y Epiclachima </li>
				<li>frente a la gasolinera  
				     "La Llave"</li>
			</ul>

		</div>

		<div class="four columns">

			<!-- Headline -->
			<h3 class="headline footer">CONTACTOS</h3>
			<span class="line"></span>
			<div class="clearfix"></div>

			<ul class="footer-links">
				<li>2575 236</li>
				<li>099 886 6491</li>
				<li>099 291 7939</li>
				<li><i class="fa fa-envelope"></i><a href="mailto:your@email.com">encofradosgranda@gmail.com</a></li>
			</ul>
		</div>

		<div class="four columns">

			<!-- Headline -->


	</div>
	<!-- Container / End -->

</div>

<!-- Footer / End -->
<!-- Footer Bottom / Start -->
<div id="footer-bottom">

	<!-- Container -->
	<!--<div class="container">

		<div class="eight columns">© Copyright 2014 by <a href="#">trizzy</a>. All Rights Reserved.</div>
		<div class="eight columns">
			<ul class="payment-icons">
				<li><img src="images/visa.png" alt="" /></li>
				<li><img src="images/mastercard.png" alt="" /></li>
				<li><img src="images/skrill.png" alt="" /></li>
				<li><img src="images/moneybookers.png" alt="" /></li>
				<li><img src="images/paypal.png" alt="" /></li>
			</ul>
		</div>

	</div>
	<!-- Container / End -->

</div>
<!-- Footer Bottom / End -->

<!-- Back To Top Button -->
<div id="backtotop"><a href="#"></a></div>

</div>


{% endblock %}
</body>
</html>

templates/home/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
LOGIN 
{% endblock title %}

{% block contenido1 %}


<!-- Titlebar
================================================== -->
<section class="titlebar">
<div class="container">
	<div class="sixteen columns">
		<h2>Inicio</h2>
		
		<nav id="breadcrumbs">
			<ul>
				
			</ul>
		</nav>
	</div>
</div>
</section>


<!-- Content
================================================== -->


<!-- Container -->
<div class="container">

	<div class="six columns centered">

		<ul class="tabs-nav my-account">
			<li class=""><a href="#tab1">Login</a></li>
			<li><a href="#tab2">Register</a></li>
		</ul>

		<div class="tabs-container">
			<!-- Login -->
			<div class="tab-content" id="tab1" style="display: none;">

				<h3 class="headline">Login</h3><span class="line" style="margin-bottom:20px;"></span><div class="clearfix"></div>

				<form method="Post" class="login">
					{% csrf_token %}
					{% load bootstrap3 %}

					
					<p class="form-row form-row-wide">
						<label for="username">Username or Email Address: <span class="required">*</span></label>
						<input type="text" class="input-text" name="username" id="username" value="" />
					</p>

					<p class="form-row form-row-wide">
						<label for="password">Password: <span class="required">*</span></label>
						<input class="input-text" type="password" name="password" id="password" />
					</p>

					<p class="form-row">
						<input type="submit" class="button" name="login" value="Login" />

						<label for="rememberme" class="rememberme">
						<input name="rememberme" type="checkbox" id="rememberme" value="forever" /> Remember Me</label>
					</p>

					<p class="lost_password">
						<a href="#" >Lost Your Password?</a>
					</p>

					
				</form>
			</div>

				<!-- Register -->
				<div class="tab-content" id="tab2" style="display: none;">

					<h3 class="headline">Register</h3><span class="line" style="margin-bottom:20px;"></span><div class="clearfix"></div>

					<form method="post" class="register">
					{% bootstrap_form user_form %}
					{% bootstrap_form cliente_form %}
						

									
						{% buttons %}
						<p class="form-row">
							<input type="submit" class="button" name="register" value="Register" />
						</p>
						{% endbuttons %}
						
					</form>
				</div>
		</div>
	</div>
</div>



<div class="margin-top-50"></div>



{% endblock %}

templates/home/producto_lista_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>LISTADO DE PRODUCTOS</h2>
<!--<a href="{% url 'producto:producto_nuevo' %}">NUEVO</a>
<a href="{% url 'producto:producto_tipo_listar' %}">TIPO-PRODUCTO</a>-->
<table  class="cart-table responsive-table">
<!--  <tr>
    <th>Nombre</th>
    <th>Precio dia</th>
    <th>Precio semanal</th>
    <th>Precio mensual</th>
    <th>Descripcion</th>
    <th>Stock</th>
    <th>Tipo producto</th>
    <th>Acción</th>                         
	
  </tr>-->

<ul>
{% for producto in productos %}


<div class="products">
	<div class="four columns">
			<figure class="product">
				<div class="mediaholder">
					
						<img alt="" src="{% static 'images/sierra.jpg' %}"/>
						<div class="cover">
							<img alt="" src="{% static 'images/sierra.jpg' %}"/>
						</div>
					</a>
					<a href="{% url 'producto:add_to_cart' producto.id 1 %}?next={{ request.get_full_path }}" class="product-button"><i class="fa fa-shopping-cart"></i> Alquilar</a>
				</div>

				<!--<a href="variable-product-page.html">-->
					<section>
						<!--<span class="product-category">{{producto.nombre}}</span>-->
						<h5>{{producto.nombre}}</h5>
						<h5>{{producto.precio_dia}}</h5>
						
						<span class="product-price">{{producdo.precio_dia}}</span>
					</section>
				</a>
			</figure>
		</div>
</div>
{% endfor %}
</ul>


	
	
{% endblock %}