Constructora/urls.py
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.contrib.auth.views import login
urlpatterns = [
    url(r'^', include('home.urls' ,namespace='home')),
    url(r'^admin/', admin.site.urls),




    # para  la app de producto


    url(r'^producto/', include('producto.urls' ,namespace='producto')),

     # para  la app de cliente

    url(r'^cliente/', include('cliente.urls' ,namespace='cliente')),


    #url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),




   

  

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cliente/urls.py
from django.conf.urls import url , include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [


	url(r'^registro/$', views.cliente_nuevo, name='cliente_nuevo'),
	url(r'^login/$', views.authentication, name='login'),
	url(r'^logout$', auth_views.logout, {'next_page': 'login/'}, name='logout'),
	url(r'^listar/$', views.cliente_listar, name='cliente_listar'),
	url(r'^eliminar/(?P<id_cliente>\d+)$', views.cliente_eliminar, name='cliente_eliminar'),
	url(r'^editar/(?P<id_cliente>\d+)$', views.cliente_editar, name='cliente_editar'),
	
	


	

]

home/urls.py
from django.conf.urls import url , include
from . import views



urlpatterns = [
	url(r'^$', views.mostrar_inicio, name='index'),
	url(r'^contactos/$', views.mostrar_contactos, name='mostrar_contactos'),
	url(r'^shopping-cart/$', views.mostrar_carro, name='mostrar_carro'),
	url(r'^quienes_somos/$', views.mostrar_quienes, name='mostrar_quienes'),
	url(r'^maquinaria/$', views.mostrar_maquinaria, name='mostrar_maquinaria'),
	url(r'^herramientas/$', views.mostrar_herramienta, name='mostrar_herramienta'),
	url(r'^detalle/$', views.mostrar_detalle, name='mostrar_detalle'),
	url(r'^login/$', views.mostrar_login , name='mostrar_login'),

	# admin

	#url(r'^administrador/$', views.mostrar_admin, name='mostrar_admin'),





	#url(r'^register/$', views.UserFormView.as_view(), name='register'),
	#url(r'^new_user/$', views.usuario),
	
	# usuarios
		
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	#url(r'^admin/',views.add_user),

]

cliente/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models

# Create your models here.


class Cliente(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	cedula =models.CharField(max_length= 200, blank=True, null=True)
	direccion =models.CharField(max_length= 200)
	telefono=models.CharField(max_length=200)
	
	 

	def __str__(self):
		return " %s - %s - %s -%s"%(self.user, self.cedula, self.direccion ,self.telefono)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Cliente.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.cliente.save()

cliente/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Cliente


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')
        labels = {
        	'first_name': 'Nombres',
        	'last_name': 'Apellidos',
        }
        widgets = {
            'password':  forms.PasswordInput(),
        }


class ClienteForm(forms.ModelForm):

	class Meta:
		model= Cliente
		fields = ('cedula', 'direccion', 'telefono')

cliente/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect
from django import forms
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.utils.translation import ugettext as _
# Create your views here.
from .forms import ClienteForm, UserForm
from .models import Cliente



def cliente_nuevo(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        cliente_form = ClienteForm(request.POST)   
        if cliente_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            cliente = Cliente.objects.get(user = user)  
            print(cliente)
            # cliente_form.cleaned_data['user'] = user
            cliente.cedula = cliente_form.cleaned_data['cedula']
            cliente.direccion = cliente_form.cleaned_data['direccion']
            cliente.telefono = cliente_form.cleaned_data['telefono']
            cliente.save()
            print(cliente)
            messages.success(request, _('Cliente creado correctamente!'))
            return redirect('cliente:cliente_listar')
    else:
        cliente_form = ClienteForm()
        user_form = UserForm()

    context = {
            'cliente_form': cliente_form,
            'user_form': user_form,
    }

    return render(request, 'cliente/cliente_nuevo_form.html', context)





def cliente_listar(request):
	clientes=Cliente.objects.all()
	context={
			'clientes': clientes,

	}
	return render(request,'cliente/cliente_listar_form.html',context)

def cliente_eliminar(request, id_cliente):
        obj_cliente = Cliente.objects.get(id=id_cliente)
        if request.method=="POST":
                obj_cliente.delete()
                return redirect('cliente:cliente_listar')

        return render(request, 'cliente/cliente_eliminar_form.html', {'cliente':obj_cliente})

def cliente_editar(request, id_cliente):
    cliente= Cliente.objects.get(id=id_cliente)
    if request.method=="POST":
          form = ClienteForm(request.POST, instance=cliente) 
          if form.is_valid():
            cliente= form.save()       
            return redirect('cliente:cliente_listar')
    else:
        form = ClienteForm(instance=cliente)

    return render(request, 'cliente/cliente_editar_form.html',{'form': form})


def authentication(request):
    response= HttpResponseRedirect(request.GET.get('next'))
    print(response)
    cliente_form = ClienteForm()
    user_form = UserForm()
    context = {
            'cliente_form': cliente_form,
            'user_form': user_form,
            'next_url': response.url,
        }
    if request.method == 'POST':
        print("AUTENTICANDO")
        username  = request.POST.get('username', None)
        password = request.POST.get('password', None)

        user = authenticate(username = username, password = password)
        if user is not None:
            login(request, user)
            return redirect('producto:producto_listar')
        else:
            messages.error(request, 'Credenciales invalidas')
            return render(request, 'cliente/login.html', context)

    else:
        print('usuario no autenticado')
        

        return render(request, 'cliente/login.html', context)
                
    return render(request, 'cliente:login', {})

templates/cliente/cliente_editar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}


{% block contenido7 %}

<form method = "POST" action='' enctype='multipart/form-data'> {% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Guardar</button>
		<a  class="btn btn-primary" href="{% url 'cliente:cliente_listar' %}"> Cancelar</a>
</form>
{% endblock %}

templates/cliente/cliente_eliminar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}



{% block contenido7 %}
		<form method="POST"> {% csrf_token %}
				<h2>¿DESEA DAR DE BAJA EL REGISTRO?</h2>
				<button type="submit">Si, eliminar</button>
				<a href="{% url 'cliente:cliente_listar' %}">Cancelar</a>
		</form>

{% endblock %}

templates/cliente/cliente_listar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>LISTADO DE CLIENTES</h2>
<a href="{% url 'cliente:cliente_nuevo' %}">NUEVO</a>
<table  class="cart-table responsive-table">
  <tr>
    <th>Nombres</th>
    <th>Apellidos</th>
    <th>Cedula</th>
    <th>Direccion</th>
    <th>telefono</th>
    <th>Acción</th>                         
	
  </tr>

<ul>
{% for cliente in clientes %}
	<tr>
		<td>{{ cliente.nombre }}</td>
		<td>{{ cliente.apellidos }}</td>
		<td>{{ cliente.cedula }}</td>
		<td>{{ cliente.direccion }}</td>
		<td>{{ cliente.telefono }}</td>
	    
	    <td>
	    	<a class="btn btn-primary" href="{% url 'cliente:cliente_editar' cliente.id %}">editar</a>
	    	<a class="btn btn-primary" href="{% url 'cliente:cliente_eliminar' cliente.id %}">dar de baja</a>
	    </td>

			
	</tr>
    
{% endfor %}
</ul>

</table>

	
	
{% endblock %}

templates/cliente/cliente_nuevo_form.html
{% extends 'base.html' %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>Registro de cliente</h2>
	
	<form  method="post" class="form">
		{% csrf_token %}
		{% load bootstrap3 %}
		{% bootstrap_form user_form %}
		{% bootstrap_form cliente_form %}
		{% buttons %}
	    <button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "star" %} Guardar
	    </button>
	     <a  class="btn btn-primary" href="{% url 'cliente:cliente_listar' %}"> Cancelar</a>

	  
	</form>
	  {% endbuttons %}
	  
	  
	</form>
	 

{% endblock %}

templates/cliente/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
LOGIN 
{% endblock title %}

{% block contenido1 %}


<!-- Titlebar
================================================== -->
<section class="titlebar">
<div class="container">
	<div class="sixteen columns">
		<h2>Inicio</h2>
		
		<nav id="breadcrumbs">
			<ul>
				
			</ul>
		</nav>
	</div>
</div>
</section>


<!-- Content
================================================== -->


<!-- Container -->
{% load bootstrap3 %}

<div class="container">
	Mensajes
    {% bootstrap_messages %}

	<div class="six columns centered">

		<ul class="tabs-nav my-account">
			<li class=""><a href="#tab1">Login</a></li>
			<li><a href="#tab2">Register</a></li>
		</ul>

		<div class="tabs-container">

			<!-- Login -->
			<div class="tab-content" id="tab1" style="display: none;">

				<h3 class="headline">Login</h3><span class="line" style="margin-bottom:20px;"></span><div class="clearfix"></div>

				<form method="Post" class="login" action="{% url 'cliente:login' %}?next={{next_url}}">
					{% csrf_token %}

					
					<p class="form-row form-row-wide">
						<label for="username">Username or Email Address: <span class="required">*</span></label>
						<input type="text" class="input-text" name="username" id="username" value="" />
					</p>

					<p class="form-row form-row-wide">
						<label for="password">Password: <span class="required">*</span></label>
						<input class="input-text" type="password" name="password" id="password" />
					</p>

					<p class="form-row">
						<input type="submit" class="button" name="login" value="Login" />

						<label for="rememberme" class="rememberme">
						<input name="rememberme" type="checkbox" id="rememberme" value="forever" /> Remember Me</label>
					</p>

					<p class="lost_password">
						<a href="#" >Lost Your Password?</a>
					</p>

					
				</form>
			</div>

				<!-- Register -->
				<div class="tab-content" id="tab2" style="display: none;">

					<h3 class="headline">Register</h3><span class="line" style="margin-bottom:20px;"></span><div class="clearfix"></div>

					<form method="post" class="register" action="{% url 'cliente:cliente_nuevo' %}?next={{next_url}}">
					{% csrf_token %}
						
					{% bootstrap_form user_form %}
					{% bootstrap_form cliente_form %}
						

									
						{% buttons %}
						<p class="form-row">
							<input type="submit" class="button" name="register" value="Register" />
						</p>
						{% endbuttons %}
						
					</form>
				</div>
		</div>
	</div>
</div>



<div class="margin-top-50"></div>



{% endblock %}