Constructora/urls.py
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from django.contrib.auth.views import login
urlpatterns = [
    url(r'^', include('home.urls' ,namespace='home')),
    url(r'^admin/', admin.site.urls),




    # para  la app de producto


    url(r'^producto/', include('producto.urls' ,namespace='producto')),

     # para  la app de cliente

    url(r'^cliente/', include('cliente.urls' ,namespace='cliente')),


    #url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),




   

  

    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.conf.urls import url , include
from . import views



urlpatterns = [
	url(r'^$', views.mostrar_inicio, name='index'),
	url(r'^contactos/$', views.mostrar_contactos, name='mostrar_contactos'),
	url(r'^shopping-cart/$', views.mostrar_carro, name='mostrar_carro'),
	url(r'^quienes_somos/$', views.mostrar_quienes, name='mostrar_quienes'),
	url(r'^maquinaria/$', views.mostrar_maquinaria, name='mostrar_maquinaria'),
	url(r'^herramientas/$', views.mostrar_herramienta, name='mostrar_herramienta'),
	url(r'^detalle/$', views.mostrar_detalle, name='mostrar_detalle'),
	url(r'^login/$', views.mostrar_login , name='mostrar_login'),

	# admin

	#url(r'^administrador/$', views.mostrar_admin, name='mostrar_admin'),





	#url(r'^register/$', views.UserFormView.as_view(), name='register'),
	#url(r'^new_user/$', views.usuario),
	
	# usuarios
		
	#url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	#url(r'^admin/',views.add_user),

]

producto/urls.py
from django.conf.urls import url , include
from . import views

urlpatterns = [


	url(r'^nuevo/$', views.producto_nuevo, name='producto_nuevo'),
	url(r'^listar/$', views.producto_listar, name='producto_listar'),
	url(r'^tipo/$', views.producto_tipo_nuevo, name='producto_tipo_nuevo'),
	url(r'^tipo_listar/$', views.producto_tipo_listar, name='producto_tipo_listar'),
	url(r'^tipo_editar/(?P<id_tipo>\d+)$', views.producto_tipo_editar, name='producto_tipo_editar'),
	url(r'^tipo_eliminar/(?P<id_tipo>\d+)$', views.producto_tipo_eliminar, name='producto_tipo_eliminar'),
	url(r'^eliminar/(?P<id_producto>\d+)$', views.producto_eliminar, name='producto_eliminar'),
	url(r'^editar/(?P<id_producto>\d+)$', views.producto_editar, name='producto_editar'),

	# url de cart

	url(r'^cart/(?P<id_producto>\d+)/(?P<quantity>\d+)$', views.add_to_cart, name='add_to_cart'),
	url(r'^get_cart/$', views.get_cart, name='get_cart'),
	url(r'^remove_from_cart/(?P<id_producto>\d+)$', views.remove_from_cart, name='remove_from_cart'),
	
	


	

]

producto/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class TipoProducto(models.Model):
	nombre =models.CharField(max_length= 200)

	def __str__(self):
		return"%s"%(self.nombre)
		


class Producto(models.Model):
	image = models.FileField(null=True, blank=True)
	nombre =models.CharField(max_length= 200)
	precio_dia =models.CharField(max_length= 200)
	precio_semanal =models.CharField(max_length= 200)
	precio_mensual =models.CharField(max_length= 200)
	descripcion =models.TextField(max_length=25)
	stock =models.CharField(max_length= 200)
	tipo_producto =models.ForeignKey(TipoProducto)

	 

	def __str__(self):
		return "%s - %s - %s - %s - %s - %s -%s"%(self.nombre, self.precio_dia, self.precio_semanal, self.precio_mensual ,self.descripcion, self.stock, self.tipo_producto)

producto/forms.py
from django.forms import ModelForm
from .models import Producto,TipoProducto



class ProductoForm(ModelForm):

	class Meta:
		model= Producto
		fields = ('__all__')


class TipoProductoForm(ModelForm):

	class Meta:
		model= TipoProducto
		fields = ('__all__')

producto/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django import forms
# Create your views here.
from .forms import ProductoForm, TipoProductoForm
from .models import Producto, TipoProducto
from cart.cart import Cart


def producto_nuevo(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)   
        if form.is_valid():
        	producto= form.save()       
        	return redirect('producto:producto_listar')
    else:
        form = ProductoForm()

    return render(request, 'producto/producto_nuevo_form.html', {'form': form})



def producto_listar(request):
	productos=Producto.objects.all()
	context={
			'productos': productos,

	}
	return render(request,'producto/producto_lista_form.html',context)

def producto_eliminar(request, id_producto):
        obj_producto = Producto.objects.get(id=id_producto)
        if request.method=="POST":
                obj_producto.delete()
                return redirect('producto:producto_listar')

        return render(request, 'producto/producto_eliminar_form.html', {'producto':obj_producto})

def producto_editar(request, id_producto):
    producto= Producto.objects.get(id=id_producto)
    if request.method=="POST":
          form = ProductoForm(request.POST, instance=producto) 
          if form.is_valid():
            producto= form.save()       
            return redirect('producto:producto_listar')
    else:
        form = ProductoForm(instance=producto)

    return render(request, 'producto/producto_editar_form.html',{'form': form})


# TIPO PRODUCTO

def producto_tipo_nuevo(request):
    if request.method == 'POST':
        form = TipoProductoForm(request.POST)   
        if form.is_valid():
            tipo= form.save()       
            return redirect('producto:producto_listar')
    else:
        form = TipoProductoForm()

    return render(request, 'producto/producto_tipo_form.html',{'form': form})


def producto_tipo_listar(request):
    tipo_producto=TipoProducto.objects.all()
    context={
            'tipo_producto': tipo_producto,

    }
    return render(request,'producto/producto_tipo_lista_form.html',context)

def producto_tipo_eliminar(request, id_tipo):
        obj_tipo = TipoProducto.objects.get(id=id_tipo)
        if request.method=="POST":
                obj_tipo.delete()
                return redirect('producto:producto_listar')

        return render(request, 'producto/producto_tipo_eliminar_form.html', {'producto':obj_tipo})

def producto_tipo_editar(request, id_tipo):
    tipo= TipoProducto.objects.get(id=id_tipo)
    if request.method=="POST":
          form = TipoProductoForm(request.POST, instance=tipo) 
          if form.is_valid():
            tipo= form.save()       
            return redirect('producto:producto_listar')
    else:
        form = TipoProductoForm(instance=tipo)

    return render(request, 'producto/producto_tipo_editar_form.html',{'form': form})


# agregar a carrito
@login_required()
def add_to_cart(request, id_producto, quantity):
    product = Producto.objects.get(id=id_producto)
    cart = Cart(request)
    
    cart.add(product, product.precio_dia, quantity)
    response= HttpResponseRedirect(request.GET.get('next'))
    return response
    
@login_required()
def remove_from_cart(request, id_producto):
    product = Producto.objects.get(id=id_producto)
    cart = Cart(request)
    cart.remove(product)
    response= HttpResponseRedirect(request.GET.get('next'))
    return response

@login_required()
def get_cart(request):
    cart= Cart(request)
    context={
        'cart': cart

    }
    return render(request, 'producto/shopping-cart.html', context)

templates/producto/producto_editar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}


{% block contenido7 %}

<form method = "POST" action='' enctype='multipart/form-data'> {% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Guardar</button>
		<a  class="btn btn-primary" href="{% url 'producto:producto_listar' %}"> Cancelar</a>
</form>
{% endblock %}

templates/producto/producto_eliminar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}



{% block contenido7 %}
		<form method="POST"> {% csrf_token %}
				<h2>¿DESEA DAR DE BAJA EL REGISTRO?</h2>
				<button type="submit">Si, eliminar</button>
				<a href="{% url 'producto:producto_listar' %}">Cancelar</a>
		</form>

{% endblock %}

templates/producto/producto_lista_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>LISTADO DE PRODUCTOS</h2>
<a href="{% url 'producto:producto_nuevo' %}">NUEVO</a>
<a href="{% url 'producto:producto_tipo_listar' %}">TIPO-PRODUCTO</a>
<table  class="cart-table responsive-table">
<!--  <tr>
    <th>Nombre</th>
    <th>Precio dia</th>
    <th>Precio semanal</th>
    <th>Precio mensual</th>
    <th>Descripcion</th>
    <th>Stock</th>
    <th>Tipo producto</th>
    <th>Acción</th>                         
	
  </tr>-->

<ul>
{% for producto in productos %}


<div class="products">
	<div class="four columns">
			<figure class="product">
				<div class="mediaholder">

					
						<img alt="" src="{% static 'images/sierra.jpg' %}"/>
						<div class="cover">
							<img alt="" src="{% static 'images/sierra.jpg' %}"/>
						</div>
					</a>
					<a href="{% url 'producto:add_to_cart' producto.id 1 %}?next={{ request.get_full_path }}" class="product-button"><i class="fa fa-shopping-cart"></i> Alquilar</a>
				</div>

				<!--<a href="variable-product-page.html">-->
					<section>
						<!--<span class="product-category">{{producto.nombre}}</span>-->
						<h5>{{producto.nombre}}</h5>
						<h5>${{producto.precio_dia}}</h5>
						<h5>{{producto.descripcion}}</h5>
						
						<!--<span class="product-price">{{producdo.precio_dia}}</span>-->
					</section>
				</a>
			</figure>
		</div>
</div>
{% endfor %}
</ul>

</table>



	
	
{% endblock %}

templates/producto/producto_nuevo_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>Creacion de producto</h2>
	
	<form  method="post" class="form">
	  {% csrf_token %}
	  {% bootstrap_form form %}
	  {% buttons %}
	    <button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "star" %} Guardar
	    </button>
	    <a  class="btn btn-primary" href="{% url 'producto:producto_listar' %}"> Cancelar</a>

	  
	</form>
	  {% endbuttons %}
	  
	  
	</form>
	 

{% endblock %}

templates/producto/producto_tipo_editar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}


{% block contenido7 %}

<form method = "POST" action='' enctype='multipart/form-data'> {% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Guardar</button>
		<a  class="btn btn-primary" href="{% url 'producto:producto_listar' %}"> Cancelar</a>
</form>
{% endblock %}

templates/producto/producto_tipo_eliminar_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}



{% block contenido7 %}
		<form method="POST"> {% csrf_token %}
				<h2>¿DESEA DAR DE BAJA EL REGISTRO?</h2>
				<button type="submit">Si, eliminar</button>
				<a href="{% url 'producto:producto_listar' %}">Cancelar</a>
		</form>

{% endblock %}

templates/producto/producto_tipo_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>Creacion Tipo producto</h2>
	
	<form  method="post" class="form">
	  {% csrf_token %}
	  {% bootstrap_form form %}
	  {% buttons %}
	    <button type="submit" class="btn btn-primary">
	      {% bootstrap_icon "star" %} Guardar
	    </button>
	    <a  class="btn btn-primary" href="{% url 'producto:producto_listar' %}"> Cancelar</a>

	  
	</form>
	  {% endbuttons %}
	  
	  
	</form>
	 

{% endblock %}

templates/producto/producto_tipo_lista_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido7 %}

<h2>lista  tipo productos</h2>
<a href="{% url 'producto:producto_tipo_nuevo' %}">NUEVO</a>
<a href="{% url 'producto:producto_listar' %}">REGRESAR</a>

<table  class="cart-table responsive-table">
  <tr>
    <th>Nombre</th>
    <th>Acción</th>
  </tr>

<ul>
{% for tipo in tipo_producto %}
	<tr>
		<td>{{ tipo.nombre }}</td>
	    
	    <td>
	    	<a class="btn btn-primary" href="{% url 'producto:producto_tipo_editar' tipo.id %}">editar</a>
	    	<a class="btn btn-primary" href="{% url 'producto:producto_tipo_eliminar' tipo.id %}">dar de baja</a>
	    </td>

			
	</tr>
    
{% endfor %}
</ul>

</table>

	
	
{% endblock %}

templates/producto/shopping-cart.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
ENCOFRADOS 
{% endblock title %}

{% block contenido1 %}
<!-- Titlebar
================================================== -->
<section class="titlebar">
<div class="container">
	<div class="sixteen columns">
		<h2>Shopping Cart</h2>
		<h3>Añadir producto</h3>
		
		<nav id="breadcrumbs">
			<ul>
				<a href="{% url 'producto:producto_listar' %}" class="button color cart-btns proceed">Añadir</a>
				
			</ul>
		</nav>
	</div>
</div>
</section>



<div class="container cart">

	<div class="sixteen columns">
		<!--<table>
			<tr>
				<th>Item</th>
				<th>Descripcion</th>
				<th>Precio</th>
				<th>Cantidad</th>
				<th>Total</th>
				<th></th>
			</tr>
			{% for item in cart %}
			<tr>
				<td>{{item.product.nombre}}</td>
				<td>{{item.product.}}</td>
				<td>{{item.unit_price}}</td>
				<td>{{item.quantity}}</td>
				<td>{{item.total_price}}</td>
			</tr>
			{% endfor %}
		</table>-->	
		<!-- Cart -->
		<table class="cart-table responsive-table">

			<tr>
				<th>Item</th>
				<th>Descripcion</th>
				<th>Precio</th>
				<th>Cantidad</th>
				<th>Total</th>
				<th>remove</th>
			</tr>
			{% for item in cart %}		
			<!-- Item #1 -->
			<tr>
				<td>{{item.product.nombre}}</td>
				<td >{{item.product.descripcion}}</td>
				<td id="price{{item.product.id}}">{{item.unit_price}}</td>
				<td>
					<form action='#'>
						<div  item_id="{{item.product.id }}" class="qtyminus"></div>
						<input id="qty_product{{item.product.id }}" type='text' name="quantity" value={{item.quantity}} class="qty" />
						<div  item_id="{{item.product.id }}" class="qtyplus"></div>
					</form>
				</td>
				<td id="total_item{{item.product.id }}" class="total_item ">{{item.total_price}} </td>
			
				<td><a href="{% url 'producto:remove_from_cart' item.product.id %}?next={{ request.get_full_path }}" class="cart-remove"></a></td>
			</tr>
			{% endfor %}
		

		</table>

			<!-- Apply Coupon Code / Buttons -->
			<table class="cart-table bottom">

				<tr>
				<th>
					<div class="cart-btns">
						<a href="{% url 'home:mostrar_login'%}" class="button color cart-btns proceed">Reservar</a>
					</div>
				</th>
				</tr>

			</table>
	</div>


	<!-- Cart Totals -->
	<div class="eight columns cart-totals">
		<h3 class="headline">Total</h3><span class="line"></span><div class="clearfix"></div>

		<table class="cart-table margin-top-5">

			<tr>
				<th>Total Reserva</th>
				<td id= "totales"><strong></strong></td>
			</tr>

			<!--<tr>
				<th>Shipping and Handling</th>
				<td>Free Shipping</td>
			</tr>

			<tr>
				<th>Order Total</th>
				<td><strong>$178.00</strong></td>
			</tr> -->

		</table>
		<br>
		<!-- <a href="#" class="calculate-shipping"><i class="fa fa-arrow-circle-down"></i> Calculate Shipping</a> -->
	</div>

</div>


<div class="margin-top-40"></div>
<script type="text/javascript">
	Calcular_totales();

	function Calcular_totales() {

		var total_item= 0;
		$(".total_item").each(function(){
			 console.log($(this).text());
			 total_item+=parseFloat($(this).text());
		});
		console.log("total de los item"+total_item);

		$("#totales").text(total_item.toFixed(2));

	 
	}


	//calculos de totales por item 
	$(".qtyminus").click(function(){
		var item_id= $(this).attr("item_id");
		console.log(item_id);
		var price=parseFloat($("#price"+item_id).text());
		console.log("precio="+price)

		var cuantity= parseFloat($("#qty_product"+item_id).val())-1;
		console.log("cantidad"+ cuantity);
		$("#qty_product"+item_id).val(cuantity);

		var total= cuantity*price;
		$("#total_item"+item_id).text(total.toFixed(2));
		Calcular_totales();
	});

	$(".qtyplus").click(function(){
		var item_id= $(this).attr("item_id");
		console.log(item_id);
		var price=parseFloat($("#price"+item_id).text());
		console.log("precio="+price)

		var cuantity= +parseFloat($("#qty_product"+item_id).val())+1;
		console.log("cantidad"+ cuantity);
		$("#qty_product"+item_id).val(cuantity);

		var total= cuantity*price;
		$("#total_item"+item_id).text(total.toFixed(2));
		Calcular_totales();


	});





</script>

{% endblock %}